# Generated by Django 4.2.7 on 2023-11-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="title",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
