# Generated by Django 4.2.7 on 2023-11-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_book_author_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="title2",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
