# Generated by Django 4.2.7 on 2023-11-20 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0003_book_title2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="title2",
        ),
    ]
